# Generated by Django 5.2.3 on 2025-06-14 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='projects',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
