# Generated by Django 5.2.3 on 2025-06-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_student_first_name_student_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
    ]
