# Generated by Django 5.2.3 on 2025-06-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_remove_student_first_name_remove_student_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='points',
            field=models.IntegerField(default=10),
        ),
    ]
