# Generated by Django 5.2.3 on 2025-06-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_alter_student_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='number_of_connections',
        ),
        migrations.AddField(
            model_name='student',
            name='connections',
            field=models.ManyToManyField(blank=True, to='Accounts.student'),
        ),
    ]
