# Generated by Django 5.2.3 on 2025-06-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_remove_student_number_of_connections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='student_avatars/'),
        ),
    ]
