# Generated by Django 5.2.3 on 2025-06-14 10:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections1', to='Accounts.student')),
                ('student2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections2', to='Accounts.student')),
            ],
            options={
                'unique_together': {('student1', 'student2')},
            },
        ),
        migrations.CreateModel(
            name='ConnectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='Accounts.student')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='Accounts.student')),
            ],
            options={
                'unique_together': {('sender', 'receiver')},
            },
        ),
    ]
