# Generated by Django 5.2.3 on 2025-06-14 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_remove_project_category_remove_project_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='invited_users',
            field=models.ManyToManyField(blank=True, related_name='invited_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joined_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
