# Generated by Django 5.2.3 on 2025-06-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_alter_student_points'),
        ('Dashboard', '0003_project_invited_users_project_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='required_fields',
            field=models.CharField(blank=True, help_text='Comma-separated fields like Web Development, AI, ML', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='required_skills',
            field=models.ManyToManyField(blank=True, to='Accounts.skill'),
        ),
    ]
