# Generated by Django 5.2.3 on 2025-06-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0012_alter_project_status_pendinginvitation_projectpost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='taskcomment',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='completion_resource_file',
            field=models.FileField(blank=True, null=True, upload_to='task_resources/'),
        ),
        migrations.AddField(
            model_name='task',
            name='completion_resource_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProjectPost',
        ),
        migrations.DeleteModel(
            name='TaskComment',
        ),
    ]
