# Generated by Django 5.2.3 on 2025-06-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0014_remove_task_completion_resource_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='verification_file',
            field=models.FileField(blank=True, null=True, upload_to='task_verifications/'),
        ),
        migrations.AddField(
            model_name='task',
            name='verification_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
